[package]
name = "mimisbrunnr-wal"
description = "Write-ahead log"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mimisbrunnr-storage = { workspace = true }
mimisbrunnr-types = { workspace = true }
bytemuck = { workspace = true }
ciborium = { workspace = true }
crc32c = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
