[package]
name = "mimisbrunnr-wal"
description = "Write-ahead log"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mimisbrunnr-types = { workspace = true }
mimisbrunnr-storage = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
crc32fast = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
