[package]
name = "mimisbrunnr-storage"
description = "Block device abstraction and on-disk layout for Mímisbrunnr"
version.workspace = true
edition.workspace = true

[dependencies]
mimisbrunnr-types = { workspace = true }
bytemuck = { workspace = true }
crc32fast = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
