[package]
name = "mimisbrunnr-storage"
description = "Block device abstraction and on-disk layout for Mímisbrunnr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytemuck = { workspace = true, features = ["min_const_generics"] }
ciborium = { workspace = true }
crc32c = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
mimisbrunnr-types = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
