[package]
name = "mimisbrunnr-meta"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mimisbrunnr-storage = { workspace = true }
mimisbrunnr-types = { workspace = true }
bytemuck = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
