[package]
name = "mimisbrunnr-index"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mimisbrunnr-types = { workspace = true }
arbitrary-int = { workspace = true }
roaring = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
