[package]
name = "mimisbrunnr-index"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mimisbrunnr-types = { workspace = true }
mimisbrunnr-storage = { workspace = true }
mimisbrunnr-meta = { workspace = true }
bytemuck = { workspace = true }
ciborium = { workspace = true }
log = { workspace = true }
roaring = { workspace = true }
serde = { workspace = true }
siphasher = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
