[package]
name = "mimisbrunnr-sql"
description = "SQL query layer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mimisbrunnr-index = { workspace = true }
mimisbrunnr-ontology = { workspace = true }
mimisbrunnr-query = { workspace = true }
mimisbrunnr-types = { workspace = true }
log = { workspace = true }
sqlparser = { workspace = true }
thiserror = { workspace = true }
