[package]
name = "mimisbrunnr-query"
description = "Query processing"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mimisbrunnr-index = { workspace = true }
mimisbrunnr-ontology = { workspace = true }
mimisbrunnr-types = { workspace = true }
ciborium = { workspace = true }
log = { workspace = true }
roaring = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
