[package]
name = "mimisbrunnr-engine"
description = "Storage engine tying all Mímisbrunnr layers together"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mimisbrunnr-index = { workspace = true }
mimisbrunnr-meta = { workspace = true }
mimisbrunnr-ontology = { workspace = true }
mimisbrunnr-pool = { workspace = true }
mimisbrunnr-query = { workspace = true }
mimisbrunnr-storage = { workspace = true }
mimisbrunnr-transform = { workspace = true }
mimisbrunnr-types = { workspace = true }
mimisbrunnr-wal = { workspace = true }
arbitrary-int = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
ciborium = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
