[package]
name = "mimisbrunnr-ontology"
description = "Ontology management"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mimisbrunnr-index = { workspace = true }
mimisbrunnr-types = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
arbitrary-int = { workspace = true }
tempfile = { workspace = true }
