[package]
name = "mimisbrunnr-watch"
description = "Query subscription engine for Mímisbrunnr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ciborium = { workspace = true }
log = { workspace = true }
mimisbrunnr-index = { workspace = true }
mimisbrunnr-ontology = { workspace = true }
mimisbrunnr-types = { workspace = true }
roaring = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

