[package]
name = "mimisbrunnr-watch"
description = "Query subscription engine for Mímisbrunnr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mimisbrunnr-types = { workspace = true }
mimisbrunnr-index = { workspace = true }
mimisbrunnr-ontology = { workspace = true }
mimisbrunnr-query = { workspace = true }
roaring = { workspace = true }
thiserror = { workspace = true }
